server:
  port: 8085

#Eureka配置，服务注册到哪里
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: springcloud-provider-zuulgateway8085 #修改Euerka上的默认描述信息
    prefer-ip-address: true #隐藏真实地址
#info配置
info:
  app.name: yancy-springcloud
  company.name: fsd.yancy_zuulgateway_study.com

#数据库连接
spring:
  application:
    name: zuulgateway
  datasource:
    url: jdbc:mysql://106.14.5.63:3306/fsd2020?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMutiQueries=true
    username: mysql
    password: 594Caoyizheng!
    driver-class-name: com.mysql.cj.jdbc.Driver

#zuul配置
zuul:
  routes:
    fsd.serviceId: iposervice
    fsd.path: /fsd/**
