server:
  port: 8083
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: package com.fsd.data
#数据库连接
spring:
  application:
    name: iposervice
  datasource:
    url: jdbc:mysql://106.14.5.63:3306/fsd2020?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMutiQueries=true
    username: mysql
    password: 594Caoyizheng!
    driver-class-name: com.mysql.cj.jdbc.Driver
